apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-db
  name: mongo-db
  namespace: k8s-apps
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-db
  type: ClusterIP
