apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: internal-app-monitor
  name: internal-app-monitor
  namespace: k8s-apps
spec:
  endpoints:
    - interval: 5s
      targetPort: 8081
      path: /actuator/prometheus
  selector:
    matchLabels:
      app: internal-app-service


