apiVersion: v1
kind: Service
metadata:
  labels:
    app: internal-app-service
    namespace: k8s-apps
  name: internal-app-service
spec:
  ports:
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: internal-app
  type: ClusterIP
